#!/bin/bash
# 服务器部署指南 - 将最新代码部署到服务器

echo "======================================"
echo "服务器代码同步和部署指南"
echo "======================================"
echo ""
echo "步骤 1: 在本地环境打包最新代码"
echo "--------------------------------------"
echo "在本地开发环境执行以下命令："
echo ""
echo "cd /workspace/projects"
echo "tar -czf tnho-latest.tar.gz \\"
echo "  --exclude='.git' \\"
echo "  --exclude='__pycache__' \\"
echo "  --exclude='*.pyc' \\"
echo "  --exclude='logs/*' \\"
echo "  --exclude='assets/uploads/*' \\"
echo "  --exclude='node_modules' \\"
echo "  --exclude='dist' \\"
echo "  ."
echo ""
echo "======================================"
echo ""
echo "步骤 2: 上传压缩包到服务器"
echo "--------------------------------------"
echo "执行以下命令上传："
echo ""
echo "scp tnho-latest.tar.gz root@47.110.72.148:/root/"
echo ""
echo "======================================"
echo ""
echo "步骤 3: 在服务器上解压和部署"
echo "--------------------------------------"
echo "SSH 登录到服务器后执行："
echo ""
echo "# 1. 备份旧版本"
echo "cd /root"
echo "mv tnho-video-api tnho-video-api.backup.$(date +%Y%m%d_%H%M%S)"
echo ""
echo "# 2. 解压新代码"
echo "mkdir -p tnho-video-api"
echo "cd tnho-video-api"
echo "tar -xzf /root/tnho-latest.tar.gz"
echo ""
echo "# 3. 确保 .env 文件存在"
echo "ls -la .env"
echo ""
echo "# 4. 重新构建并启动容器"
echo "docker-compose down"
echo "docker-compose build --no-cache"
echo "docker-compose up -d"
echo ""
echo "# 5. 查看日志"
echo "docker logs -f tnho-video-api"
echo ""
echo "======================================"
echo ""
echo "步骤 4: 验证部署"
echo "--------------------------------------"
echo "等待容器启动后执行："
echo ""
echo "# 检查容器状态"
echo "docker ps | grep tnho"
echo ""
echo "# 测试健康检查"
echo "curl http://localhost:8000/health"
echo ""
echo "# 测试 API 文档"
echo "curl http://localhost:8000/docs"
echo ""
echo "# 测试 Nginx 代理"
echo "curl http://localhost/health"
echo ""
echo "======================================"
